export default function Contact() {
    return (
        <div className="bg-gray-900 h-screen w-screen flex flex-col items-center justify-center py-24 px-4">
        <div>
        <div className="flex justify-center p-4">
            <div className="font-bold text-3xl text-white ml-1">Contact</div>
            <div className="font-bold text-3xl text-blue-400">Me!</div>
        </div>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

        </div>
    
    
    
        <form className="w-full max-w-md">
        <div className="flex flex-col space-y-4">
        <div className="grid grid-cols-2 gap-2">
            <input type="text" placeholder="Full Name" className="bg-gray-900 border border-blue-400 rounded-md py-2 px-4 focus:outline-none focus:border-blue-400 text-white" />
            <input type="email" placeholder="Email Address" className="bg-gray-900 border border-blue-400 rounded-md py-2 px-4 focus:outline-none focus:border-blue-400 text-white" />
        </div>
            <div className="grid grid-cols-2 gap-2">
            <input type="tel" placeholder="Mobile Number" className="bg-gray-900 border border-blue-400 rounded-md py-2 px-4 focus:outline-none focus:border-blue-400 text-white" />
            <input type="text" placeholder="Email Subject" className="bg-gray-900 border border-blue-400 rounded-md py-2 px-4 focus:outline-none focus:border-blue-400 text-white" />
            </div>
            <textarea placeholder="Your Message" className="bg-gray-900 border border-blue-400 h-56 rounded-md py-4 px-4 resize-none focus:outline-none focus:border-blue-400 text-white"></textarea>
            </div>
        <div className="flex justify-center">
        <button type="submit" className="bg-blue-500 w-24 hover:bg-blue-400 flex justify-center text-blue-950 font-bold py-2 px-4 rounded-md mt-4 focus:outline-none focus:shadow-outline ">Submit</button>
        </div>
            
        </form>
    
        <footer className="text-sm text-gray-400 mt-8">
            Copyright © 2023 by Codebud. All Rights Reserved.
        </footer>
        </div>
    );
    
}